import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import { makeFixture, fixture } from './support/renderer-fixture.mjs';
fixture.template = await fs.readFile(new URL('../engine/assets/renderer-inject.js', import.meta.url),'utf8');
test('local video attaches without a navigated iframe, pauses when hidden, and fully releases on restore', async()=>{
  const f=makeFixture();
  vm.runInNewContext(f.payloadFor({video:{url:'http://127.0.0.1:4567/'+'a'.repeat(64)+'/video.mp4'}}),f.context);
  const state=f.window.__CODEX_DREAM_SKIN_STATE__;
  const v=f.document.getElementById('codex-dream-skin-video-frame');
  assert.equal(v.contentWindow,undefined,'A network iframe must not be used for local video');
  assert.equal(typeof state.attachVideoBlob,'function');
  assert.equal(v.muted,true);
  assert.equal(v.loop,true);
  assert.equal(v.getAttribute('tabindex'),'-1');
  assert.equal(v.getAttribute('aria-hidden'),'true');
  assert.equal(v.src,'');
  state.videoBlobUrl='blob:app://-/fixture';
  state.attachVideoBlob(state.videoBlobUrl);
  assert.equal(v.src,state.videoBlobUrl);
  f.listeners.get('video:playing')();
  assert.equal(f.attrs.get('data-dream-video-state'),'playing');
  f.document.hidden=true; f.listeners.get('document:visibilitychange')();
  assert.equal(v.paused,true);
  f.document.hidden=false; f.listeners.get('document:visibilitychange')();
  assert.equal(v.paused,false);
  state.videoUpload={chunks:['partial']};
  const lateError=f.listeners.get('video:error');
  state.cleanup();
  lateError();
  assert.equal(f.document.getElementById('codex-dream-skin-video-frame'),null);
  assert.equal(f.document.getElementById('codex-dream-skin-video-overlay'),null);
  assert.equal(f.attrs.has('data-dream-video-state'),false);
  assert.equal(f.listeners.has('document:visibilitychange'),false);
  assert.equal(f.listeners.has('video:playing'),false);
  assert.equal(state.videoUpload,undefined);
  assert.ok(f.revoked.includes('blob:app://-/fixture'));
});
